config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'
  resources :users, only: [:index, :show, :edit , :update] do
    resource :follows, only: [:create, :destroy]
    get :favorites, on: :member
    get :follows, on: :member
    get :followers, on: :member
    get :search, on: :collection
  end
  resources :posts do
    get :search, on: :collection
    resource :favorites, only: [:create, :destroy]
    get :timeline, on: :collection
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user, presence: true
  validates :user_id, uniqueness: { scope: :post_id }
  validates :post, presence: true

end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :inverse_follower, class_name: "User"

  validates :follower, presence: true
  validates :inverse_follower, presence: true
  validates :inverse_follower_id, uniqueness: { scope: :follower_id }

end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :image_url, ImageUploader
  belongs_to :post

  # validates :post_id, presence: true

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy

  has_many :images ,dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true

  validates :post, presence: true

  def favorited_by? user
    favorites.where(user_id: user.id).exists?
  end

  # def self.search(search)
  #   return Post.all unless search

  #   split_keyword = search.split(/[[:blank:]]+/)

  #   split_keyword.each do |search|
  #     next if search == ""
  #     Post.where('post LIKE(?)', "%#{search}%")
  #   end

  # end

  default_scope { order(created_at: :desc) }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, presence: true, uniqueness: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favorites, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post

  has_many :follows, foreign_key: :follower_id
  has_many :inverse_followers, through: :follows
  has_many :inverse_follows, foreign_key: :inverse_follower_id, class_name: "Follow"
  has_many :followers, through: :inverse_follows


  def favorited_by? user
    favorites.where(user_id: user.id).exists?
  end

  def followed_by? user
    inverse_follows.where(follower_id: user.id).exists?
  end

  mount_uploader :image, ImageUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :bio, :image])
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  # before_filter :require_login

  def create
    @post = Post.find(params[:post_id])
    @favorite = current_user.favorites.build(post: @post)
    @favorite.save
      # respond_to do |format|
      #   format.js { flash[:notice] = "お気に入りに登録しました" }
      # end
    # else
    #   redirect_to posts_url , alert: "このツイートはお気に入りに登録できません"
    # end
  # if @favorite.save
      # notice: "お気に入りに登録しました"
  #   else
  #     redirect_to posts_url , alert: "このツイートはお気に入りに登録できません"
  #  end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @favorite = current_user.favorites.find_by!(post_id: params[:post_id])
    @favorite.destroy
    # redirect_back(fallback_location: root_path ,notice: "お気に入りを解除しました")
  end

end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    @user.inverse_follows.create(follower: current_user)
    # if @user.inverse_follows.create(follower: current_user)
    #   redirect_back(fallback_location: root_path ,notice: "フォローしました")
    # else
    #   redirect_back(fallback_location: root_path ,notice: "フォローできません")
    # end
  end

  def destroy
    @user = User.find(params[:user_id])
    follow = @user.inverse_follows.find_by(follower: current_user.id)
    follow.destroy
    # redirect_back(fallback_location: root_path ,notice: "フォローを解除しました")
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post

  def index
    @posts = Post.includes(:user, :images).order("created_at DESC")
  end

  def new
  end

  def timeline
    @posts = Post.eager_load(user: :inverse_follows).where(follows: { follower_id: current_user.id })
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path , notice: '投稿しました'
    else
      redirect_back(fallback_location: root_path , alert: "投稿できません")
    end
    @post.user = current_user
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_back(fallback_location: root_path ,alert: "投稿を削除しました")
  end

  def search
    redirect_to root_path if params[:keyword] == ""
    split_keyword = params[:keyword].split(/[[:blank:]]+/)
    @posts = []
    split_keyword.each do |keyword|
      next if keyword == ""
      @posts += Post.where('post LIKE(?)', "%#{keyword}%")
    end
    @posts.uniq!
    #重複した投稿を削除する
    respond_to do |format|
      format.html
      format.json
    end
  end

  private
  def post_params
    params.require(:post).permit(:post, images_attributes: [:image_url, :_destroy, :id]).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.new
    @post.images.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_post

  def show
    @user = User.find(params[:id])
    @name = current_user.name
    @posts = current_user.posts.order("created_at DESC")
  end

  def edit
    @user = current_user
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def favorites
    @user = User.find(params[:id])
  end

  def follows
    @user = User.find(params[:id])
  end

  def followers
    @user = User.find(params[:id])
  end

  def search
    redirect_to root_path if params[:keyword] == ""
    split_keyword = params[:keyword].split(/[[:blank:]]+/)
    @users = []
    split_keyword.each do |keyword|
      next if keyword == ""
      @users +=User.where('name LIKE(?)', "%#{keyword}%")
    end
    @users.uniq!
    #重複したユーザーを削除する
    respond_to do |format|
      format.html
      format.json
    end
    respond_to do |format|
      format.html
      format.json
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :bio, :image)
  end

  def set_post
    @post = Post.new
    @post.images.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/create.js.erb
$('#favorites_buttons_<%= @post.id %>').html("<%= j(render partial: 'layouts/favorite', locals: {post: @post}) %>");

app/views/favorites/destroy.js.erb
$('#favorites_buttons_<%= @post.id %>').html("<%= j(render partial: 'layouts/favorite', locals: {post: @post}) %>");

app/views/follows/create.js.erb
$('.follows_buttons_<%= @user.id %>').html("<%= j(render partial: 'layouts/follow', locals: {user: @user}) %>");

app/views/follows/destroy.js.erb
$('.follows_buttons_<%= @user.id %>').html("<%= j(render partial: 'layouts/follow', locals: {user: @user}) %>");

app/views/layouts/_favorite.html.haml
.favorite-btn
  - if post.favorited_by? current_user
    = link_to  post_favorites_path(post), method: :delete , remote: true do
      = icon 'fa', 'heart' ,class: 'fav-remove'
  - else
    = link_to  post_favorites_path(post), method: :post , remote: true do
      = icon 'fa', 'heart' ,class: 'fav-add'

  -if post.favorites.count != 0
    .favorite-count
      = post.favorites.count

app/views/layouts/_follow.html.haml
- if user.followed_by? current_user
  = link_to "フォロー中", user_follows_path(user), method: :delete, remote: true
- else
  = link_to "フォローする", user_follows_path(user), method: :post, remote: true

app/views/layouts/_header.html.haml
.header
  .header__nav
    .logo-img
      = link_to posts_path , class: "user"  do
        %sapn{style:"font-family: 'Kaushan Script', cursive"}
          MuNi
    - if user_signed_in?
      .search-box
        = form_with url:"/posts/search" , local: true, method: :get, class: "search-form search-post" do |form|
          = form.text_field :keyword, placeholder: "投稿を検索", class: "search-input search-input-post"
          -# = form.submit "検索", class: "search-btn"
        = form_with url:"/users/search" , local: true, method: :get, class: "search-form user" do |form|
          = form.text_field :keyword, placeholder: "ユーザーを検索", class: "search-input search-input-user"
          -# = form.submit "検索", class: "search-btn"

    %ul.user-nav
      - if user_signed_in?
        %li.dropdown-btn
          = icon('fas' ,'cogs')
          %ul.dropdown
            %li
              = link_to '設定',  edit_user_path(current_user)
            %li
              = link_to 'ログアウト', destroy_user_session_path, method: :delete
      - else
        .first-view-menu
          %li
            = link_to '登録する', new_user_registration_path
          %li
            = link_to 'ログイン', new_user_session_path

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/_post.html.haml
.post
  .user-icon
    = link_to user_path(post.user) do
      - if post.user.image.present?
        = image_tag post.user.image.url
      - else
        .no-image
          no image

  .content
    .content-top
      .user-name
        = link_to user_path(post.user) do
          = post.user.name
      .post-content
        = post.post
        .post-content__image
          -if post.images.present?
            - post.images.each do |image|
              = link_to image.image_url.url ,'data-lightbox':image ,:rel => "lightbox" do
                = image_tag image.image_url.url , class:'popup-image'
      .post-time
        = post.created_at.to_s(:datetime)

    .content-bottom
      .favorite-wrapper{:id => "favorites_buttons_#{post.id}"}
        = render partial: 'layouts/favorite', locals: { post: post }

      .destoroy-follow-wrapper
        - if user_signed_in? && current_user.id == post.user_id
          .destroy-btn
            = link_to "削除" ,"/posts/#{post.id}", method: :delete
        - else
          .follow-btn{:class => "follows_buttons_#{post.user.id}"}
            = render partial: 'layouts/follow', locals: { user: post.user }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content:  "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title MuNi
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = stylesheet_link_tag{href:"https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css", rel:"stylesheet"}
    %script{ src: "https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"}
    %script{ src: "https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js",type:"text/javascript"}
    %meta{content: "width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0", name: "viewport"}

    -# = stylesheet_link_tag{href:"https://cdnjs.cloudflare.com/ajax/libs/drawer/3.2.2/css/drawer.min.css", rel:"stylesheet"}
    -# %script{ src: "https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"}
    -# %script{ src: "https://cdnjs.cloudflare.com/ajax/libs/iScroll/5.2.0/iscroll.min.js"}
    -# %script{ src: "https://cdnjs.cloudflare.com/ajax/libs/drawer/3.2.2/js/drawer.min.js"}
  %body

    %header
      #wrapper
        .nav-toggle
          = icon 'fas', 'bars' , class: "nav-toggle__icon"
        = link_to  posts_path  , class: "title"  do
          %sapn{style: "font-family: 'Kaushan Script', cursive"}
            MuNi
        =link_to new_post_path  , class: "new-post" do
          %i.fa.fa-feather
        .gloval-nav
          %nav
            %ul
              - if user_signed_in?
                %li
                  = link_to "マイページ" , user_path(current_user)
                %li
                  = link_to "設定" , edit_user_path(current_user)
                %li
                  = link_to 'ログアウト' , destroy_user_session_path , method: :delete
              - else
                %li
                  = link_to '登録する' , new_user_registration_path
                %li
                  = link_to 'ログイン' , new_user_session_path

    .header
      = render "layouts/header"

    = yield

app/views/posts/_main_content.html.haml
.main-content
  -# = render 'layouts/notifications'

  .info-header
    .self-info
      すべての投稿

  .posts
    = render partial: 'layouts/post', collection:@posts

app/views/posts/_post.html.haml
.post
  .user-icon
    = link_to user_path(post.user) do
      - if post.user.image.present?
        = image_tag post.user.image.url
      - else
        .no-image
          no image
  .content
    .content-top
      .user-name
        = link_to user_path(post.user) do
          = post.user.name
      .post-content
        = post.post
        .post-content__image
          - post.images.each do |image|
            -if image.image_url.present?
              = link_to image.image_url.url ,'data-lightbox':image ,:rel => "lightbox" do
                = image_tag image.image_url.url ,class:'popup-image'
      .post-time
        = post.created_at.to_s(:datetime)
    .content-bottom
      .favorite-wrapper
        .favorite-btn
        - if post.favorited_by? current_user
          = link_to  post_favorites_path(post), method: :delete do
            = icon 'fa', 'heart' ,class: 'fav-remove'
        - else
          = link_to  post_favorites_path(post), method: :post do
            = icon 'fa', 'heart' ,class: 'fav-add'

        -if post.favorites.count != 0
          .favorite-count
          = post.favorites.count

      .destoroy-follow-wrapper
        - if user_signed_in? && current_user.id == post.user_id
          .destroy-btn
            = link_to "削除" ,"/posts/#{post.id}", method: :delete 
        - else
          .follow-btn
            - if post.user.followed_by? current_user
              = link_to "フォロー中", user_follows_path(post.user), method: :delete
            - else
              = link_to "フォローする", user_follows_path(post.user), method: :post

-# .div#popup-background
-# img#popup-item

app/views/posts/_side_bar.html.haml
.side-bar
  .user-info
    = link_to user_path(current_user) do
      - if current_user.image.present?
        .user-icon
          = image_tag current_user.image.url
      - else
        .no-image
          no image

      .user-name
        #{current_user.name}
      - if current_user.bio.present?
        .user-bio
          #{current_user.bio}

  .user-activity
    .tweets-num
      = link_to  user_path(current_user) do
        .text
          投  稿
        .num
          #{current_user.posts.count} 件
    .favorites
      = link_to favorites_user_path(current_user) do
        .text
          お気に入り
        .num
          #{current_user.favorites.count} 件
    .follow-num
      = link_to follows_user_path(current_user) do
        .text
          フォロー中
        .num
          #{current_user.inverse_followers.count} 人

    .follower-num
      = link_to  followers_user_path(current_user) do
        .text
          フォロワー
        .num
          #{current_user.followers.count} 人

    .all-posts
      = link_to  posts_path do
        .text
          すべての投稿

    .follow-posts
      = link_to  timeline_posts_path(current_user) do
        .text
          フォロー中の投稿

  .form
    = form_for @post do |f|
      .form-post
        = f.text_area :post , class: 'form-text' , placeholder: 'いまどうしてる？',rows:"3"
        #image-box
          .btm-wrapper
            #image-form
              = f.fields_for :images  do |i|
                .js-file_group{"data-index" => "#{i.index}"}
                  %label
                    = i.file_field  :image_url , class: 'js-file no-disply'
                    %span 画像を添付
                    %i.far.fa-image.image-icon.js-file
            = f.submit 'つぶやく' , class: 'form-btn'
          #previews

app/views/posts/index.html.haml
.wrapper{role:"main"}
  = render 'layouts/notifications'
  = render "main_content"
  = render "side_bar"

app/views/posts/new.html.haml
.form
  = form_for @post do |f|
    .form-post
      = f.text_area :post , class: 'form-text' , placeholder: 'いまどうしてる？',rows:"3"
      #image-box
        .btm-wrapper
          #image-form
            = f.fields_for :images  do |i|
              .js-file_group{"data-index" => "#{i.index}"}
                %label
                  = i.file_field  :image_url , class: 'js-file no-disply'
                  %span 画像を添付
                  %i.far.fa-image.image-icon.js-file
          = f.submit 'つぶやく' , class: 'form-btn'
        #previews

app/views/posts/search.html.haml
.wrapper
  .main-content
    = render 'layouts/notifications'
    .info-header
      .self-info
        検索結果

    - if @posts.empty?
      %p
        一致する投稿がありません
    -else
      .posts
        = render partial: 'layouts/post', collection: @posts

  = render "side_bar"

app/views/posts/timeline.html.haml
.wrapper
  .main-content
    = render 'layouts/notifications'
    .info-header
      .self-info
        フォローしている人の投稿

    - if @posts.empty?
      %p
        表示する投稿がありません
    -else
      .posts
        = render partial: 'layouts/post', collection: @posts

  = render "side_bar"

app/views/users/_user-status.html.haml
.another-info__box
  .another-info__box__image
    - if @user.image.present?
      = image_tag @user.image.url
    - else
      .no-image
        no image

  .another-info__box__profile
    .another-info__box__profile__name
      = @user.name
    .another-info__box__profile__bio
      = @user.bio

    .another-activity
      .tweets-num
        = link_to  user_path(@user) do
          .text
            投 稿
          .num
            #{@user.posts.count}件

      .favorites
        = link_to favorites_user_path(@user) do
          .text
            お気に入り
          .num
            #{@user.favorites.count}件

      .follow-num
        = link_to follows_user_path(@user) do
          .text
            フォロー中
          .num
            #{@user.inverse_followers.count}人

      .follower-num
        = link_to  followers_user_path(@user) do
          .text
            フォロワー
          .num
            #{@user.followers.count}人

app/views/users/_user.html.haml
.user
  .user-icon
    = link_to user_path(user) do
      - if user.image.present?
        = image_tag user.image.url
      - else
        .no-image
          no image
  .user-name
    = link_to user_path(user) do
      #{user.name}

  .follow-btn{:class => "follows_buttons_#{user.id}"}
    = render partial: 'layouts/follow', locals: { user: user }

app/views/users/edit.html.haml
.user-wrapper
  .edit-form
    %h1
      アカウント情報の編集
    = form_for (current_user),class:"form" do |f|
      .edit-form__image
        - if @user.image.present?
          .current-image
            = image_tag @user.image.url
        - else
          .no-image
            no-image
        .image-label-wrapper
          %label{ class: 'image_input_btn'}
            画像を選択
            =icon('fas', 'image')
            =f.file_field :image , class: "image_form"
          %p
            ※正方形に調整されます※

      .edit-form__name
        =f.label :名前 ,class:'label'
        =f.text_field :name ,class:'name-form'

      .edit-form__bio
        =f.label :自己紹介 ,class:'label'
        =f.text_field :bio ,class:'bio-form'

      .edit-form__email
        =f.label :メールアドレス ,class:'label'
        =f.email_field :email ,class:'email-form'

      .edit-btn
        =f.submit "更新する" ,class:'update-btn'

    .pass
      = link_to edit_user_registration_path do
        パスワードの変更 / アカウント削除

app/views/users/favorites.html.haml
.wrapper
  .main-content
    = render 'layouts/notifications'
    .info-header
      - if current_user.id == @user.id
        .self-info
          あなたのお気に入り
        .self-activity#self-activity
          = render partial: 'user-status', locals: { user: @user }
      - else
        .another-info
          .another-info__header
            #{@user.name}さんのお気に入り
          = render partial: 'user-status', locals: { user: @user }

    - if @user.favorites.empty?
      %p
        お気に入りの投稿はまだありません
    -else
      .posts
        = render partial: 'layouts/post', collection: @user.favorite_posts

  = render "posts/side_bar"

app/views/users/followers.html.haml
.wrapper
  .main-content
    = render 'layouts/notifications'
    .info-header
      - if current_user.id == @user.id
        .self-info
          あなたのフォロワー
        .self-activity#self-activity
          = render partial: 'user-status', locals: { user: @user }
      -else
        .another-info
          .another-info__header
            #{@user.name}さんのフォロワー
          = render partial: 'user-status', locals: { user: @user }

    - if @user.followers.empty?
      %p
        フォロワーがいません
    - else
      .users
        = render partial: 'user', collection: @user.followers

  = render "posts/side_bar"

app/views/users/follows.html.haml
.wrapper
  .main-content
    = render 'layouts/notifications'
    .info-header
      - if current_user.id == @user.id
        .self-info
          あなたがフォローしている人
        .self-activity#self-activity
          = render partial: 'user-status', locals: { user: @user }
      -else
        .another-info
          .another-info__header
            #{@user.name}さんがフォローしている人
          = render partial: 'user-status', locals: { user: @user }

    - if @user.inverse_followers.empty?
      %p
        フォローしている人がいません
    - else
      .users
        = render partial: 'user', collection: @user.inverse_followers

  = render "posts/side_bar"

app/views/users/search.html.haml
.wrapper
  .main-content
    = render 'layouts/notifications'
    .info-header
      .self-info
        検索結果

    - if @users.empty?
      %p
        一致するユーザーはいません
    - else
      .users
        = render partial: 'user', collection: @users

  = render "posts/side_bar"

app/views/users/show.html.haml
.wrapper
  .main-content
    = render 'layouts/notifications'
    .info-header
      - if current_user.id == @user.id
        .self-info
          あなたの投稿
        .self-activity#self-activity
          = render partial: 'user-status', locals: { user: @user }
      -else
        .another-info
          .another-info__header
            #{@user.name}さんの投稿
          = render partial: 'user-status', locals: { user: @user }

    - if @user.posts.empty?
      %p
        投稿がありません
    - else
      .posts
        = render partial: 'layouts/post', collection: @user.posts

  = render "posts/side_bar"